export const MODELS_API_BASE_URL = 'http://127.0.0.1:5000/api'
export const MODELS_API_BOOKS_URL = MODELS_API_BASE_URL + '/books'

export const MODELS_API_USER_BOOK_RECOMMENDATIONS = MODELS_API_BASE_URL + '/user_book_recommendations'
export const MODELS_API_USER_BOOK_RECOMMENDATIONS_TRAIN_LOGGED_IN_USER = MODELS_API_USER_BOOK_RECOMMENDATIONS + '/train_logged_in_user'