export const MODELS_API_BASE_URL = 'http://127.0.0.1:5000/api'
export const MODELS_API_BOOKS_URL = MODELS_API_BASE_URL + '/books'
export const MODELS_API_BOOKS_RECOMMENDATIONS_URL = MODELS_API_BOOKS_URL + '/recommendations'
export const MODELS_API_AUTH = MODELS_API_BASE_URL + '/auth'
export const MODELS_API_AUTH_LOGIN = MODELS_API_AUTH + '/login'
export const MODELS_API_AUTH_REGISTER = MODELS_API_AUTH + '/register'
export const MODELS_API_ME = MODELS_API_BASE_URL + '/me'