export const MODELS_API_BASE_URL = 'http://127.0.0.1:5000/api'

export const MODELS_API_BOOKS_URL = MODELS_API_BASE_URL + '/books'
export const MODELS_API_BOOKS_SEARCH_URL = MODELS_API_BOOKS_URL + '/search'
export const MODELS_API_BOOKS_RECOMMENDATIONS_URL = MODELS_API_BOOKS_URL + '/recommendations'
export const MODELS_API_BOOKS_RATE_URL = MODELS_API_BOOKS_URL + '/rate'

export const MODELS_API_AUTH_URL = MODELS_API_BASE_URL + '/auth'
export const MODELS_API_AUTH_LOGIN_URL = MODELS_API_AUTH_URL + '/login'
export const MODELS_API_AUTH_REGISTER_URL = MODELS_API_AUTH_URL + '/register'
export const MODELS_API_AUTH_LOGOFF = MODELS_API_AUTH_URL + '/logoff'
export const MODELS_API_AUTH_CHECK_SESSION_URL = MODELS_API_AUTH_URL + '/check_session'

export const MODELS_API_ME_URL = MODELS_API_BASE_URL + '/me'

export const MODELS_API_USER_BOOK_RECOMMENDATIONS = MODELS_API_BASE_URL + '/user_book_recommendations'
export const MODELS_API_USER_BOOK_RECOMMENDATIONS_TRAINING_STATUS = MODELS_API_USER_BOOK_RECOMMENDATIONS + '/training_status'
export const MODELS_API_USER_BOOK_RECOMMENDATIONS_TRAIN_LOGGED_IN_USER = MODELS_API_USER_BOOK_RECOMMENDATIONS + '/train_logged_in_user'

export const MODELS_API_CATEGORIES = MODELS_API_BASE_URL + '/categories'
export const MODELS_API_CATEGORIES_INDEX = MODELS_API_CATEGORIES
export const MODELS_API_CATEGORIES_LIKE = MODELS_API_CATEGORIES + '/like'
export const MODELS_API_CATEGORIES_ME = MODELS_API_CATEGORIES + '/me'

export const MODELS_API_AUTHORS = MODELS_API_BASE_URL + '/authors'
export const MODELS_API_AUTHORS_INDEX = MODELS_API_AUTHORS